/*
 * This source file was generated by the Gradle 'init' task
 */
package memtestsjava;

public class App {
    public static void main(String[] args) {
        HowToClassTypedInitializer.main(args);
    }
}
